### PR TITLE
Allow filtering results by workorder assignee

### PR DESCRIPTION
**Pull request by darachcawley**
@wtrocki could you have a look please?

### CODE REVIEW

**Comment by wtrocki** [comment]
@darachcawley Can I get more info here about motivation for this change. 

Result will have assignee field. Each workorder has assignee and array of results. Are we trying to say that workorder can be shared with other people and steps can be finished by different persons?

**Comment by darachcawley** [comment]
@wtrocki sure.
At the moment, the results are tied to a workorder but in order to filter down the results to the workorders assigned to a particular driver, a custom handler is required to get the list of workorders assigned to that driver/assignee and then the list of results retrieved. 
When scaling up, it would be more efficient to remove this call to workorders and filter the results returned directly, reducing the number of db calls per sync call.
Let me know if you need more information.

**Comment by wtrocki** [comment]
@darachcawley Thanks for explanation.

**Comment by wtrocki** [comment]
Thanks for contribution. Closing in fav of other PR

**Pull request closed without merging**
